# signals.py - Signal description
# ----------------------------------------------------------------
# WARNING: Do not modify this file. It is automatically generated
#          from signal files. Any modification will be lost the
#          next time the file is generated.

"""
Signal description file generated from:
    test/tc_back.rb
Generated by:
    test/tc_linx4pyback.rb
"""

import ogre
from ctypes import *


class ABSFLInput(Structure):
    """Signal description for struct ABSFLInput"""

    _fields_ = [
        ('ABSFL_w', c_uint),
        ('ABSFL_v', c_uint),
        ('ABSFL_wheelABS', c_uint),
        ('ABSFL_R', c_uint),
    ]

ABSFL_INPUT_SIG_NO = 13121 
class ABSFL_INPUT_SIG(Structure):
    """Signal description for signal ABSFL_INPUT_SIG"""

    _fields_ = [
        ('sig_no', c_uint),
        ('input', ABSFLInput),
    ]
    def __init__(self):
        super(Structure, self).__init__()
        self.sig_no = 13121

class ABSFLStateTrace(Structure):
    """Signal description for array ABSFLStateTrace"""

    _fields_ = [
        ('w', c_uint),
        ('wheelABS', c_uint),
        ('torqueABS', c_uint),
        ('v', c_uint),
        ('R', c_uint),
        ('state', c_uint),
    ]

ABSFL_OUTPUT_SIG_NO = 13122 
class ABSFL_OUTPUT_SIG(Structure):
    """Signal description for signal ABSFL_OUTPUT_SIG"""

    _fields_ = [
        ('sig_no', c_uint),
        ('num_states', c_uint),
        ('states', ABSFLStateTrace * 10),
    ]
    def __init__(self):
        super(Structure, self).__init__()
        self.sig_no = 13122

# ----
class LINX_SIGNAL(Union):
    '''
    LinxAdapter Signal
    '''
    _fields_ = [
        ("sig_no", c_uint),
        ("absfl_input_sig", ABSFL_INPUT_SIG),
        ("absfl_output_sig", ABSFL_OUTPUT_SIG),
    ]

# End of file
