# signals.py - Signal description
# ----------------------------------------------------------------
# WARNING: Do not modify this file. It is automatically generated
#          from signal files. Any modification will be lost the
#          next time the file is generated.

"""
Signal description file generated from:
    test/tc_back.rb
Generated by:
    test/tc_linx4pyback.rb
"""

import ogre
from ctypes import *

LINX_SIGSELECT = int
class testenum:
    ENUM1 = 0
    ENUM2 = 1
    ENUM3 = 2

class struct_type(Structure):
    """Signal description for struct struct_type"""

    _fields_ = [
        ('a', c_int),
        ('b', c_int),
    ]

OUTPUT_SIG_NO = 13121 
class OUTPUT_SIG(Structure):
    """Signal description for signal OUTPUT_SIG"""

    _fields_ = [
        ('sig_no', c_int),
        ('output', c_int),
        ('array_val',  * 10),
        ('array_size', c_int),
        ('byte_val', c_ubyte),
        ('struct_val', struct_type),
    ]
    def __init__(self):
        super(Structure, self).__init__()
        self.sig_no = 13121

# ----
class LINX_SIGNAL(Union):
    '''
    LinxAdapter Signal
    '''
    _fields_ = [
        ("sig_no", c_uint),
        ("output_sig", OUTPUT_SIG),
    ]

# End of file
